Repository AY2021S2-CS2103T-T13-3/tp, pull requests merged in 2021-04, with the labels that each got.

#113 Update UG/DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AliasSequenceDiagram.puml
  docs/images/AliasSequenceDiagram.png
  docs/images/UiNewDeleteAlias.png
  docs/images/UiUseDeleteAlias.png
Labels: documentation

#171 Fix incorrect edit format in command summary
  docs/UserGuide.md
Labels: documentation

#170 Fix PE dry-run bugs
  docs/UserGuide.md
  docs/team/yeoutzer.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: documentation, enhancement

#115 Add manual testing for add and sort commands
  docs/DeveloperGuide.md
Labels: documentation

#176 Polishing work
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/flashcard/SortOptions.java
Labels: documentation

#179 Add effort for sort feature
  docs/DeveloperGuide.md
Labels: documentation

#180 Update UG/DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AliasActivityDiagram.puml
  docs/images/AliasActivityDiagram.png
  docs/team/marc-97.md
  docs/team/marcus.md
Labels: documentation

#185 Refactor build.gradle
  build.gradle
Labels: refactor

#182 Add effort section on DG, update PPP
  docs/DeveloperGuide.md
  docs/team/zenlyj.md
Labels: documentation

#189 Update my PPP
  docs/team/marc-97.md
Labels: documentation
