Repository AY2021S2-CS2103T-T13-3/tp, pull requests merged in 2021-03, with the labels that each got.

#36 Update user stories
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#52 Add view command
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/flashcard/Flashcard.java
  src/main/java/seedu/address/model/flashcard/exceptions/DuplicateFlashcardException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/FlashbackCard.java
  src/main/java/seedu/address/ui/FlashbackViewCard.java
  src/main/java/seedu/address/ui/FlashcardListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/FlashbackViewCard.fxml
  src/main/resources/view/FlashcardListCard.fxml
  src/main/resources/view/FlashcardListPanel.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FlashBackParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/flashcard/PriorityTest.java
  src/test/java/seedu/address/model/flashcard/QuestionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/flashcard/UniqueFlashcardListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedFlashcardTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: enhancement

#64 [EditCmd] Update tests, user guide and dev guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditFlashcardDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: documentation, refactor

#63 Update find command to enable the ability to search by priority and tag
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindPriorityCommand.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/flashcard/CategoryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/flashcard/PriorityContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/flashcard/QuestionContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: enhancement

#61 Update User Guide and Developer Guide for find feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/findComputerResult.png
  docs/team/yeoutzer.md
Labels: documentation

#65 [Marcus] Add UndoCommand
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/FlashBackParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedFlashBack.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
Labels: enhancement

#81 Implement Stats functionality
  README.md
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/UiMainWindowComponents.png
  docs/images/UiReviewModeComponents.png
  docs/images/UiReviewModeWindow.png
  docs/index.md
  docs/team/yeoutzer.md
  docs/team/zenlee.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/ReviewManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ReviewCommand.java
  src/main/java/seedu/address/logic/commands/StatsCommand.java
  src/main/java/seedu/address/logic/commands/UpdateStatisticsCommand.java
  src/main/java/seedu/address/logic/parser/FlashBackParser.java
  src/main/java/seedu/address/logic/parser/StatsCommandParser.java
  src/main/java/seedu/address/model/flashcard/Category.java
  src/main/java/seedu/address/model/flashcard/Flashcard.java
  src/main/java/seedu/address/model/flashcard/Statistics.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedFlashcard.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CustomTextArea.java
  src/main/java/seedu/address/ui/FlashbackCard.java
  src/main/java/seedu/address/ui/FlashbackStats.java
  src/main/java/seedu/address/ui/FlashbackViewCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReviewMode.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/FlashbackStats.fxml
  src/main/resources/view/FlashbackViewCard.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReviewMode.fxml
  src/test/data/JsonFlashBackStorageTest/invalidAndValidFlashcardFlashBack.json
  src/test/data/JsonFlashBackStorageTest/invalidFlashcardFlashBack.json
  src/test/data/JsonSerializableFlashBackTest/duplicateFlashcardFlashBack.json
  src/test/data/JsonSerializableFlashBackTest/invalidFlashcardFlashBack.json
  src/test/data/JsonSerializableFlashBackTest/typicalFlashcardFlashBack.json
  src/test/java/seedu/address/logic/ReviewManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ReviewCommandTest.java
  src/test/java/seedu/address/logic/commands/StatsCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateStatisticsCommandTest.java
  src/test/java/seedu/address/logic/parser/StatsCommandParserTest.java
  src/test/java/seedu/address/model/flashcard/StatisticsTest.java
  src/test/java/seedu/address/storage/JsonAdaptedFlashcardTest.java
  src/test/java/seedu/address/testutil/FlashcardBuilder.java
  src/test/java/seedu/address/testutil/TypicalFlashcards.java
Labels: enhancement

#82 Add ability for FlashBack to filter flashcards
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FlashBackParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/flashcard/FlashcardContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/flashcard/FlashcardFilterPredicate.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FlashBackParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/flashcard/FlashcardFilterPredicateTest.java
Labels: enhancement

#86 Add sort functionality
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FlashBackParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/flashcard/SortOptions.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/flashcard/SortOptionsTest.java
Labels: enhancement

#83 Update UserGuide
  docs/UserGuide.md
  docs/images/filterCharlesRecursionResult.png
  docs/images/filterComRanResult.png
  docs/images/filterMidFormulaResult.png
  docs/images/findComputerFormulaResult.png
  docs/images/findComputerResult.png
  docs/images/findPhyResult.png
Labels: documentation

#90 Update UG & DG with statistics functionality
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StatsSequenceDiagram.puml
  docs/images/StatsSequenceDiagram.png
  docs/images/UiStatsIndex.png
  docs/images/UiStatsNoIndex.png
  docs/team/vuminhhieu.md
  src/main/java/seedu/address/logic/commands/StatsCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: documentation

#92 Add UG and DG for sort and diagram for Model component
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/UiAfterSort.png
  docs/images/UiBeforeSort.png
Labels: documentation

#89 Update Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterActivityDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/images/FilterActivityDiagram.png
  docs/images/FilterSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FlashBackParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/flashcard/FlashcardContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/flashcard/FlashcardFilterPredicate.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: documentation

#93 Update UG/DG for undo/redo
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/UiAfterRedo.PNG
  docs/images/UiAfterRedo.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: documentation

#102 Update UG and portfolio
  docs/AboutUs.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/team/linhns.md
Labels: documentation

#107 Add border to pictures for sort command
  docs/UserGuide.md
  docs/images/UiAfterSort.png
  docs/images/UiBeforeSort.png
Labels: documentation

#103 Minor update to developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/filterCharlesRecursionResult.png
  docs/images/filterComRanResult.png
  docs/images/filterMidFormulaResult.png
  docs/images/findComputerFormulaResult.png
  docs/images/findComputerResult.png
  docs/images/findPhyResult.png
  docs/team/yeoutzer.md
Labels: documentation

#104 Update UG and DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/images/UiReviewAnsFalse.png
  docs/images/UiReviewAnsTrue.png
  docs/images/UiReviewExit.png
  docs/images/UiReviewHide.png
  docs/images/UiReviewModeNoAnswer.png
  docs/images/UiReviewNext.png
  docs/images/UiReviewPrev.png
  docs/team/vuminhhieu.md
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/model/flashcard/UniqueFlashcardList.java
  src/main/java/seedu/address/ui/FlashcardListPanel.java
  src/main/resources/view/FlashcardListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/model/FlashBackTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/flashcard/FlashcardTest.java
  src/test/java/seedu/address/model/flashcard/UniqueFlashcardListTest.java
  src/test/java/seedu/address/storage/JsonFlashBackStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: documentation

#105 Update DG with NFRs, instructions for manual testing
  docs/DeveloperGuide.md
  docs/images/StatsSequenceDiagram.png
  src/main/java/seedu/address/model/flashcard/Statistics.java
Labels: documentation

#106 Update UG, add black border to images
  docs/UserGuide.md
  docs/images/UiEditResult.png
  docs/images/UiStatsIndex.png
  docs/images/UiStatsNoIndex.png
Labels: documentation
